# Generated by Django 4.2.6 on 2023-11-03 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SteamRoguelike',
            new_name='GameRoguelike',
        ),
    ]
